# Physics 404/604

## Computational Physics 

# Matrix Computing

## Two masses on a string problem:

The problem is from the textbook "COMPUTATIONAL PHYSICS", 3rd Ed, by RH Landau, MJ Paez, and CC Bordeianu

Very hard to solve analytically.

Write down the equations, and we have 9 variables (treat sin, cos as variables), and 9 nonlinear equations.

\begin{equation}
f_{i}(x_{1},x_{2},...,x_{N})=0, \qquad i=1,2,....,N
\end{equation}

\begin{equation}
f(y)=\left[ \begin{array}{c} f_{1}(\bf{y}) \\ f_{2}(\bf{y}) \\ f_{3}(\bf{y}) \\ f_{4}(\bf{y}) \\ f_{5}(\bf{y}) \\ f_{6}(\bf{y}) \\ f_{7}(\bf{y}) \\ f_{8}(\bf{y}) \\ f_{9}(\bf{y}) \end{array}\right] = \left[ \begin{array}{c} 3x_{4}+4 x_{5} +4 x_{6} - 8 \\ 3 x_{1}+4 x_{2} -4 x_{3} \\ x_{7}x_{1} - x_{8} x_{2} -10 \\ x_{7}x_{4} - x_{8} x_{5} \\ x_{8}x_{2} + x_{9}x_{3} -20 \\ x_{8}x_{5}-x_{9}x_{6} \\ x_{1}^2+x_{4}^2-1 \\ x_{2}^2+x_{5}^2-1 \\ x_{3}^2+x_{6}^2-1 \end{array}\right] =0 
\end{equation}

Make a guess ($x_{1},...x_{9}$), and then correct it ($\Delta x_{1},...,\Delta x_{9}$), we have
\begin{equation}
f_{i}(x_{1}+\Delta x_{1}, x_{2}+\Delta x_{2}, ..., x_{9}+\Delta x_{9})=0 \qquad, i=1,...,9
\end{equation}
We can expand it using Taylor series
\begin{equation}
f_{i}(x_{1}+\Delta x_{1}, x_{2}+\Delta x_{2}, ..., x_{9}+\Delta x_{9})\simeq f_{i}(x_{1},...,x_{9})+\sum_{j=1}^{9}\frac{\partial f_{i}}{\partial x_{j}}\Delta x_{j}=0 \qquad i=1,...,9
\end{equation}

\begin{equation}
\left[ \begin{array}{c} f_{1}\\ f_{2}\\ \ddots \\ f_{9} \end{array}\right] + \begin{bmatrix} \partial f_{1}/\partial x_{1} & \partial f_{1}/\partial x_{2} & ... & \partial f_{1}/\partial x_{9} \\ \partial f_{2}/\partial x_{1} & \partial f_{2}/\partial x_{2} & ... & \partial f_{2}/\partial x_{9} \\ \ddots \\ \partial f_{9}/\partial x_{1} & \partial f_{9}/\partial x_{2} & ... & \partial f_{9}/\partial x_{9}\end{bmatrix}\left[ \begin{array}{c} \Delta x_{1} \\ \Delta x_{2} \\ \ddots \\ \Delta x_{9} \end{array}\right] =0 
\end{equation}

So we want to solve the matrix equation
\begin{equation}
F'\Delta {\bf{x}}=-\bf{f}
\end{equation}
Here we use bold font for a vector, the captal letter to represent a matrix

# Matrix Computing

Matrix computing is used extensively in physics, engineering, math, ...

## 1) Solve a system of linear equations

\begin{eqnarray}
9x_{1}+13x_{2}+5x_{3}+2x_{4}=7\\
x_{1}+11x_{2}+7x_{3}+6x_{4}=8\\
3x_{1}+7x_{2}+4x_{3}+x_{4}=9\\
6x_{1}+1x_{2}+7x_{3}+10x_{4}=10
\end{eqnarray}

We can write the equations in the matrix form
\begin{equation}
\begin{bmatrix} 9 & 13 & 5 & 2 \\ 
          1 & 11 & 7 & 6 \\ 
          3 & 7 & 4 & 1 \\ 
          6 & 1 & 7 & 10\end{bmatrix} \left[ \begin{array}{c} x_{1} \\ x_{2} \\ x_{3} \\ x_{4} \end{array}\right] = \left[ \begin{array}{c} 7 \\ 8 \\ 9 \\ 10 \end{array}\right]
\end{equation}


Generally, 
\begin{equation}
A\bf{x}=\bf{b}
\end{equation}
where A is known N$\times$N matrix, $\bf{x}$ is an unknown vector of length N, and $\bf{b}$ is a known vector of length N.

Several ways to solve it:   
* solve it directly by Gaussian elimination or lower-upper (LU) decomposition  
* invese A and $\bf{x}=A^{-1}\bf{b}$



## Prerequisite: Use arrays

Be careful with arrays 

1) track indices 
![From textbook](http://physics.oregonstate.edu/~landaur/Books/CPbook/eBook/Notebooks/HTML/Figs/Fig6_3.png)
Row-major order used for matrix storage in Python, C and Java : 
a[3,3] (a[row, column])is stored as a[0,0], a[0,1], a[0,2], a[1,0], a[1,1], a[1,2], a[2,0], ...

2) memory usage (4D array with 100 elements in each direction)

In [1]:
### we can use list to represent array
a=[1,2,3]

### but normally use Numpy package, has a lot more support for numerical arrays

import numpy as np
vector1 = np.array([1, 2, 3, 4, 5])
matrix1 = np.array([[0,2],[1,3]])
print(matrix1, matrix1[0,1])

[[0 2]
 [1 3]] 2


In [2]:

#Notice that * operation is element operation
print(matrix1*matrix1)

[[0 4]
 [1 9]]


In [5]:
import numpy as np
np.arange(12)  # list of 12 ints

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
np.arange(12).reshape(3,4) # create, shape to 3x4 array (3 rows, 4 columns)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
a=np.arange(12).reshape(3,4)
a.shape # shape 

(3, 4)

In [5]:
a.ndim # dimension

2

In [6]:
a.size # size of a (number of elements)

12

In [7]:
a.T  # transpose method

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [8]:
# Slicing
print(a[:2, :])  # 0:2 means 0 and 1, first two rows

stuff= np.zeros(10, float) # one way to initialize an array
t=np.arange(4)
stuff[3:7]=np.sqrt(t+1) #notice that it can imput an array and output an array.
print(stuff)

[[0 1 2 3]
 [4 5 6 7]]
[0.         0.         0.         1.         1.41421356 1.73205081
 2.         0.         0.         0.        ]


In [40]:
# initialize array with some value
stuff= np.ones(10, float)*3.
print(stuff)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [10]:
# Write a program to carry out the dot product of matrix A (a_{1,1}, ...) and vector B (b_{1},...b_{4})
# 
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])
c=np.zeros(4)

for i in range(4):
    for j in range(4):
        c[i]= ## write a code for the dot product 
        
print(c)
## write a code for the dot product 


[232. 218. 123. 213.]


In [11]:
# exercise, 1) generate a 4x4 2-D array with elements 1,2,...16. 
# 2) Swap the row and column 
# 3) generate another 4 (row)x5 (column) 2-D array with elements 1,2,...20. 
# 4) slice the first 4 column to make it a 4x4 array
# 5) multiply these 2 4x4 arrys together (elementwise), and print out the first row.


### Several array products

In [43]:
import numpy as np
np.dot(a,b)

array([232., 218., 123., 213.])

In [44]:
# array can be float, complex types... 
# If you want matrix dot 
matrix1 = np.array([[0.,1.],[1.,3.]])
print(np.dot(matrix1,matrix1))

[[ 1.  3.]
 [ 3. 10.]]


In [45]:
# if you want element product
print(matrix1*matrix1)

[[0. 1.]
 [1. 9.]]


In [46]:
#or
print(np.multiply(matrix1,matrix1))

[[0. 1.]
 [1. 9.]]


## Gaussian Elimination

To solve
\begin{eqnarray}
a_{1,1}x_1+a_{1,2}x_{2}+...+a_{1,n}x_{n}=b_1\\
a_{2,1}x_1+a_{2,2}x_{2}+...+a_{2,n}x_{n}=b_2\\
...=...\\
a_{n,1}x_{1}+a_{n,2}x_{2}+...+a_{n,n}x_{n}=b_{n}
\end{eqnarray}



## How Gaussian elimination works

Write an augmented matrix

\begin{bmatrix} a_{1,1} & a_{1,2} & ... &a_{1,n} &b_1 \\ 
          a_{2,1} & a_{2,2} & ... & a_{2,n} &b_2 \\
          \ddots & \ddots & \ddots\\  
          a_{n,1} & a_{n,2} & ... & a_{n,n} &b_{n}\end{bmatrix} 


On this matrix you may make exactly three operations:

    Swap rows
    Add one row onto another
    Multiply every factor of one row with a constant

You want to get a triangular matrix. So you subsequently eliminate one variable from the system of equations until you have a matrix like this:

\begin{bmatrix} \alpha_{1,1} & \alpha_{1,2} & ... &\alpha_{1,n} &\beta_1 \\ 
          0 & \alpha_{2,2} & ... & \alpha_{2,n} &\beta_2 \\
          \ddots & \ddots & \ddots\\  
          0 & 0 & ... & \alpha_{n,n} &\beta_{n}\end{bmatrix} 
          
How to do this:

Step 1: Partial Pivoting: Search for maximum in the first column and swap the maximum row with current row (column by column)

Step 2: Make all rows below this one 0 in the first column

For every $i$, define $c=-a_{k,i}/a_{i,i}$ and $a'_{k,j}=a_{k,j}+c*a_{i,j}$ for $j\geqslant i$

Step 3: Get $x_{n}$ from the last equation, going all the way back to $x_{1}$

In [14]:


def gauss(A):
    n = len(A)

    for i in range(0, n):
        # Search for maximum in this column
        maxEl = abs(A[i][i])
        maxRow = i
        for k in range(i+1, n):
            if abs(A[k][i]) > maxEl:
                maxEl = abs(A[k][i])
                maxRow = k

        # Swap maximum row with current row (column by column)
        for k in range(i, n+1):
            tmp = A[maxRow][k]
            A[maxRow][k] = A[i][k]
            A[i][k] = tmp

        # Make all rows below this one 0 in current column
        for k in range(i+1, n):
            c = # write a code for c for the k row
            for j in range(i, n+1):
                if i == j:
                    A[k][j] = 0
                else:
                    A[k][j] = # write a code for updating A_{k,j} for each element in this row

    # Solve equation Ax=b for an upper triangular matrix A
    x = [0 for i in range(n)]
    for i in range(n-1, -1, -1):
        x[i] = A[i][n]/A[i][i]
        for k in range(i-1, -1, -1):
            A[k][n] -= A[k][i] * x[i]
    return x



In [15]:
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])
aa=np.copy(a)    #deep copy of an array
bb=np.copy(b) #deep copy of an array
b=b[:,np.newaxis]
A=np.append(a,b,axis=1)
print(A)
x = gauss(A)
print(x)
print(np.dot(aa,x)-bb)

[[ 9. 13.  5.  2.  7.]
 [ 1. 11.  7.  6.  8.]
 [ 3.  7.  4.  1.  9.]
 [ 6.  1.  7. 10. 10.]]
[0.17297979797979737, -0.8768939393939387, 4.131944444444444, -1.9084595959595962]
[ 0.00000000e+00  0.00000000e+00 -1.77635684e-15 -7.10542736e-15]


In [49]:
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])

# Solve Ax=b directly
x=np.linalg.solve(a,b)
print('x=',x)
print(np.dot(a,x)-b)

x= [ 0.1729798  -0.87689394  4.13194444 -1.9084596 ]
[-3.55271368e-15  0.00000000e+00  0.00000000e+00  0.00000000e+00]


### Why need partial pivoting?

Here is an example. Assume two-digit rounding arithmetic.
\begin{eqnarray}
0.0001𝑥+𝑦=3\\
x+2y=5
\end{eqnarray}

One step Gaussian elimination gives:
\begin{eqnarray}
0.0001𝑥+𝑦=3\\
−9998𝑦=−29995
\end{eqnarray}

After rounding:
\begin{eqnarray}
0.0001𝑥+𝑦=3\\
−10000𝑦=−30000
\end{eqnarray}

The solution is (0,3)
after rounding, but the true solution is (−1.0002,3.0001). 

## Gauss-Seidel Iterative Method (Optional)

Make a guess and do correction

\begin{eqnarray}
a_{11}x_{1}+a_{12}x_{2}+...+a_{1n}x_{n}=b_{1}\\
a_{21}x_{1}+a_{22}x_{2}+...+a_{2n}x_{n}=b_{2}\\
...\\
a_{n1}x_{1}+a_{n2}x_{2}+...+a_{nn}x_{n}=b_{n}
\end{eqnarray}

We assume the diagonal elements $a_{jj}$ to be nonzero, or, we switch the equations to make them nonzero. We can rewrite it as

\begin{eqnarray}
x_{1} = t_{1}+s_{12}x_{2}+...+s_{1n}x_{n}\\
x_{2} = s_{21}x_{1}+t_{2}+...+s_{2n}x_{n}\\
...\\
x_{n} = s_{n1}x_{1}+s_{n2}x_{2}+...t_{n}
\end{eqnarray}
So we can write it as the matrix form  
$\bf{x}$=S$\bf{x}$+t  
With initial guess $x^{(0)}=t$, we can build the solution using the recurrence relation  
$\bf{x^{(k)}}$=S$\bf{x^{k-1}}$+t, k=1,2,...
or
\begin{equation}
x_{i}^{(k)}=\sum_{j\neq i}^{n}s_{ij}x_{j}^{(k-1)}+t_{i}\qquad i=1,2,...,n
\end{equation}
This is called Jacobi method. With a slight modification, we get a more efficient
so-called Gauss-Seidel method:
\begin{equation}
x_{i}^{(k)}=\sum_{j=1}^{i-1}s_{ij}x_{j}^{(k)}+\sum_{j=i+1}^{n}s_{ij}x_{j}^{(k-1)}+t_{i}\qquad i=1,2,...,n
\end{equation}
Use the most recently updated solution components $x_{i}^{k}$ instead of those from previous steps, as soon as they become available. 

The iteration stops when 
\begin{equation}
max_{i}|\Delta_{i}^{(k)}/x_{i}^{k}|\leq \epsilon
\end{equation}

Convergence: 
A must be strictly diagonally dominant 
\begin{equation}
|a_{ii}|>\sum_{j\neq i}|a_{ij}|,\qquad i=1,2,...,n|
\end{equation}
In reality, use
\begin{equation}
|a_{ii}|>max_{j\neq i}|a_{ij}|,\qquad i=1,2,...,n|
\end{equation}
There are situations that the solution won't converge.

For normal system, having a symmetric positive-definite coefficient matrix,
the Gauss-Seidel process is always converging. To make it a normal system
\begin{equation}
A^{T}\cdot A\cdot x=A^{T}\cdot b
\end{equation}

In [ ]:

#============================================================================
def GaussSeidel(a, b, x, n, init):
# Copy right, code from Titus textbook. 
#----------------------------------------------------------------------------
#  Solves linear system a x = b by the Gauss-Seidel method.
#  Convergence is ensure by left-multiplying the system with a^T.
#  a    - coefficient matrix (n x n)
#  b    - vector of constant terms
#  x    - initial approximation of solution (input); solution (output)
#  n    - order of system
#  err  - maximum relative error of the solution components
#  init - initialization option: 0 - refines initial approximation 
#                                1 - initializes solution
#----------------------------------------------------------------------------
   eps = 1e-10                                 # relative precision criterion
   itmax = 10000                                    # max no. of iterations

   s = [[0]*(n) for i in range(n)]           # matrices of reduced system
   t = [0]*(n)

   for i in range(n):                         # matrices of normal system
      for j in range(i+1):                      # by multiplication with aT
         s[i][j] = 0e0                            # store result in s and t
         for k in range(n): s[i][j] += a[k][i]*a[k][j]
         s[j][i] = s[i][j]

      t[i] = 0e0
      for j in range(n): t[i] += a[j][i]*b[j]

   for i in range(n):                # matrices s and t of reduced system
      f = -1e0/s[i][i]; t[i] /= s[i][i]
      for j in range(n): s[i][j] *= f

   if (init):
      for i in range(n): x[i] = t[i]                # initialize solution

   for k in range(itmax):                            # loop of iterations
      err = 0e0
      for i in range(n):
         delta = t[i]                                            # correction
         for j in range(n): delta += s[i][j]*x[j]
         x[i] += delta                        # new approximation to solution
         if (x[i]): delta /= x[i]                            # relative error
         if (np.fabs(delta) > err): err = np.fabs(delta)            # maximum error
       #  print('delta,err',delta,err)
            
      if (err <= eps): break                              # check convergence

   if (k > itmax-2): print("GaussSeidel: max. no. of iterations exceeded !")

   return err

In [ ]:
import numpy as np
a=np.array([[9.,13.,5.,2.],[1.,11.,7.,6.],[3.,7.,4.,1.],[6.,1.,7.,10.]])
b=np.array([7.,8.,9.,10.])
x=np.array([1.,1.,1.,1.])

GaussSeidel(a, b, x, 4, 1)
print('x=',x)
print(np.dot(a,x)-b)

## Use NumPy's linalg Package

### Solve A$\bf{x}$=$\bf{b}$

In [1]:
import numpy as np
A= np.array([[1.,2.,3.],[22.,32.,42],[55.,66.,100.]])
b = np.array([1.,2.,3.])
print(A,b)

[[  1.   2.   3.]
 [ 22.  32.  42.]
 [ 55.  66. 100.]] [1. 2. 3.]


In [2]:
# Solve Ax=b directly
x=np.linalg.solve(A,b)
print('x=',x)
print('Residual= ',np.dot(A,x)-b)

x= [-1.4057971  -0.1884058   0.92753623]
Residual=  [2.22044605e-16 0.00000000e+00 0.00000000e+00]


In [3]:
# Solve Ax=b using the inversion of A
B=np.linalg.inv(A)
print(np.dot(B,b))

[-1.4057971  -0.1884058   0.92753623]


In [4]:
print('x=', np.dot(B,b))
print('Residual= ',np.dot(A,np.dot(B,b))-b)

x= [-1.4057971  -0.1884058   0.92753623]
Residual=  [0. 0. 0.]


## Back to the two balls on string problem

In [7]:
""" From "COMPUTATIONAL PHYSICS", 3rd Ed, Enlarged Python eTextBook  
    by RH Landau, MJ Paez, and CC Bordeianu
    Copyright Wiley-VCH Verlag GmbH & Co. KGaA, Berlin;  Copyright R Landau,
    Oregon State Unv, MJ Paez, Univ Antioquia, C Bordeianu, Univ Bucharest, 2015.
    Support by National Science Foundation"""

# NewtonNDanimate.py:      MultiDimension Newton Search
from numpy import *
from vpython import *
from numpy.linalg import solve


scene = canvas(title='String and masses configuration',
     width=500, height=500) # set the camera

tempe = curve(x=range(0,500),color=color.black)

n = 9
eps = 1e-3
deriv = zeros( (n, n), float)
f = zeros( (n), float)
x = array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1., 1., 1.])

def plotconfig():
    for obj in scene.objects:
        obj.visible=0                  # Erase previous configuration
    L1 = 3.0
    L2 = 4.0
    L3 = 4.0
    xa = L1*x[3]                # L1*cos(th1)
    ya = L1*x[0]                # L1 sin(th1)
    xb = xa+L2*x[4]             # L1*cos(th1)+L2*cos(th2)
    yb = ya+L2*x[1]             # L1*sin(th1)+L2*sen(th2)
    xc = xb+L3*x[5]             # L1*cos(th1)+L2*cos(th2)+L3*cos(th3)
    yc = yb-L3*x[2]             # L1*sin(th1)+L2*sen(th2)-L3*sin(th3)
    mx = 100.0                  # for linear coordinate transformation
    bx = -500.0                 # from 0=< x =<10
    my = -100.0                 # to    -500 =<x_window=>500
    by = 400.0                  # same transformation for y
    xap = mx*xa+bx              # to keep aspect ratio
    yap = my*ya+by
    ball1 = sphere(pos=vector(xap,yap,0), color=color.cyan,radius=15) 
    xbp = mx*xb+bx
    ybp = my*yb+by
    ball2 = sphere(pos=vector(xbp,ybp,0), color=color.cyan,radius=25) 
    xcp = mx*xc+bx
    ycp = my*yc+by
    x0 = mx*0+bx
    y0 = my*0+by
    line1 = curve(pos=[vector(x0,y0,0),vector(xap,yap,0)], color=color.yellow,radius=4)
    line2 = curve(pos=[vector(xap,yap,0),vector(xbp,ybp,0)], color=color.yellow,radius=4)
    line3 = curve(pos=[vector(xbp,ybp,0),vector(xcp,ycp,0)], color=color.yellow,radius=4)
    topline = curve(pos=[vector(x0,y0,0),vector(xcp,ycp,0)], color=color.red,radius=4)

def F(x, f):                                       # F function
    f[0] = 3*x[3]  +  4*x[4]  +  4*x[5]  -  8.0
    f[1] = 3*x[0]  +  4*x[1]  -  4*x[2]
    f[2] = x[6]*x[0]  -  x[7]*x[1]  -  10.0
    f[3] = x[6]*x[3]  -  x[7]*x[4]
    f[4] = x[7]*x[1]  +  x[8]*x[2]  -  20.0
    f[5] = x[7]*x[4]  -  x[8]*x[5]
    f[6] = pow(x[0], 2)  +  pow(x[3], 2)  -  1.0
    f[7] = pow(x[1], 2)  +  pow(x[4], 2)  -  1.0
    f[8] = pow(x[2], 2)  +  pow(x[5], 2)  -  1.0
    
def dFi_dXj(x, deriv, n):                           # Derivatives
    h = 1e-4                                             
    for j in range(0, n):
         temp = x[j]
         x[j] = x[j] +  h/2.
         F(x, f)                                                 
         for i in range(0, n):  deriv[i, j] = f[i] 
         x[j] = temp
    for j in range(0, n):
         temp = x[j]
         x[j] = x[j] - h/2.
         F(x, f)
         for i in range(0, n): deriv[i, j] = (deriv[i, j] - f[i])/h
         x[j] = temp
         
for it in range(1, 100):
      rate(1)                            # 1 second between graphs
      F(x, f)                              
      dFi_dXj(x, deriv, n)   
      B = array([[-f[0]], [-f[1]], [-f[2]], [-f[3]], [-f[4]], [-f[5]],\
			[-f[6]], [-f[7]], [-f[8]]])      
      sol = solve(deriv, B)
      dx = sol#take(sol, (0, ), 1)               # First column of sol
      for i in range(0, n):
        x[i]  = x[i]  +  dx[i]
      plotconfig()
      errX = errF = errXi = 0.0
      endi=0
      for i in range(0, n):
        if ( x[i] !=  0.): errXi = abs(dx[i]/x[i])
        else:  errXi = abs(dx[i])
        if ( errXi > errX): errX = errXi                            
        if ( abs(f[i]) > errF ):  errF = abs(f[i])        
        if ( (errX <=  eps) and (errF <=  eps) ): endi=1
      if(endi==1): break  
      
print('Number of iterations = ', it, "\n Final Solution:")
for i in range(0, n):
        print('x[', i, '] =  ', x[i])

<IPython.core.display.Javascript object>

Number of iterations =  8 
 Final Solution:
x[ 0 ] =   0.7610026986802356
x[ 1 ] =   0.26495380629721876
x[ 2 ] =   0.8357058303073955
x[ 3 ] =   0.6487487163497032
x[ 4 ] =   0.9642611069149696
x[ 5 ] =   0.5491773558227531
x[ 6 ] =   17.1602096454316
x[ 7 ] =   11.545279619176393
x[ 8 ] =   20.27157798931466





## 2)  Solve the eigenvalue problem (Optional)
\begin{equation}
A\bf{x}=\lambda\bf{x}
\end{equation}
where $\bf{x}$ is an unknown vector and $\lambda$ is an unknown parameter. Using the above method won't work since we have unknowns on both sides of the equation.

This is harder to solve, since the solution only exists for certain, if any, values of $\lambda$. We manipulate the equation
\begin{equation}
[A-\lambda I]\bf{x}=0
\end{equation}
If $[A-\lambda I]^{-1}$ exists, it leads to the trivial solution $\bf{x}=0$. The inverse of $[A-\lambda I]$ fails to exists if 
\begin{equation}
det[A-\lambda I]=0
\end{equation}
The $\lambda$ values satisfie this equation are the eigenvalues.  If you are only interested in eigenvalues, you need to calculate the determinant first and search $\lambda$ to make the equation equal 0.  

The traditional way to solve both the eigenvalues and the eigenvectors is diagonalization. Gradually change A to a diagonal 
\begin{equation}
UAU^{-1}=\begin{bmatrix} \lambda^{'}_{1} & 0 & ... &0 \\ 0 & \lambda^{'}_{2} & ... & 0 \\ 0 & 0 & \lambda^{'}_{3} & ... \\ 0 & ... &0 &\lambda^{'}_{N} \end{bmatrix}
\end{equation}
\begin{equation}
UA(U^{-1}U)\bf{x}=\lambda U\bf{x}
\end{equation}
\begin{equation}
\begin{bmatrix} \lambda^{'}_{1} & 0 & ... &0 \\ 0 & \lambda^{'}_{2} & ... & 0 \\ 0 & 0 & \lambda^{'}_{3} & ... \\ 0 & ... &0 &\lambda^{'}_{N} \end{bmatrix} U\bf{x} = \lambda U\bf{x}
\end{equation}
The first eigenvalue is $\lambda^{'}_{1}$ and the first eigenvector (U$\bf{x}$) is $(1,0,...)$, ...  
So $\bf{x}$ is $U^{-1}\hat{e_{1}}$. Overal the eigenvalues are $\lambda^{'}_{i}$ and the eigenvectors are 
\begin{equation}
\bf{x_{i}}=U^{-1}\hat{e_{i}}
\end{equation}
That is the eigenvectors are the columns of the matrix $U^{-1}$

### Solve eigenvalue problem

In [3]:
import numpy as np
I=np.array([[2./3.,-1./4.],[-1./4.,2./3.]])
print(I)
eigenvalues, eigenmatrix = np.linalg.eig(I)
print('Eigenvalues', eigenvalues, '\n Eigenmatrix', eigenmatrix)
print('Eigenvector',eigenmatrix[:,0],eigenmatrix[:,1])

[[ 0.66666667 -0.25      ]
 [-0.25        0.66666667]]
Eigenvalues [0.91666667 0.41666667] 
 Eigenmatrix [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
Eigenvector [ 0.70710678 -0.70710678] [0.70710678 0.70710678]


In [4]:
eigenvector1=np.array([eigenmatrix[0,0],eigenmatrix[1,0]])
LHS = np.dot(I,eigenvector1)
RHS = eigenvector1*eigenvalues[0]
print('LHS-RHS',LHS-RHS)

print(eigenvector1)
# an easier way to get the first coloumn
print(eigenmatrix[:,0])

LHS-RHS [ 1.11022302e-16 -1.11022302e-16]
[ 0.70710678 -0.70710678]
[ 0.70710678 -0.70710678]
